### ISSUE TITLE
Refactor hacky fix for bedrock models

### ISSUE THREAD

**Issue by maciejmajek** [RobotecAI/rai#53]
Claude models tend to reply to a previous tuple of (AiMsg, ToolMessage) with a AiMsg without a tool calls. This causes a problem, because when the model is coupled with tools, boto3 raises an error saying that 
```
ValueError: Error raised by bedrock service: An error occurred (ValidationException)
when calling the InvokeModel operation: Your API request included an `assistant` message in the final position,
which would pre-fill the `assistant` response. When using tools, pre-filling the `assistant` response is not supported.
```
This is a fix that temporarily solves that issue. 
https://github.com/RobotecAI/rai-private/blob/af241f9ae108e36385a7ef0f159773c70dc551e8/src/rai/scenario_engine/scenario_engine.py#L156-L161

Full trace:
<details><summary>Details</summary>
<p>
```
2024-07-02 18:53:09 mmajek-2204 botocore.credentials[71381] INFO Found credentials in environment variables.
2024-07-02 18:53:09 mmajek-2204 botocore.credentials[71381] INFO Found credentials in environment variables.
2024-07-02 18:53:14 mmajek-2204 rai.scenario_engine.tool_runner[71381] INFO Running tool: Ros2TopicTool with args: {'command': 'list'}
2024-07-02 18:53:14 mmajek-2204 rai.scenario_engine.tool_runner[71381] INFO Successfully ran tool: Ros2TopicTool. Output: CompletedProcess(args='ros2 topic list', returncode=0, stdout=b'/parameter_events\n/rosout\n', stderr=b'')
2024-07-02 18:53:17 mmajek-2204 rai.scenario_engine.tool_runner[71381] INFO Running tool: GetOccupancyGridTool with args: {'topic': '/map'}
2024-07-02 18:53:27 mmajek-2204 SingleMessageGrabber[71381] ERROR Failed to receive message of type Metaclass_OccupancyGrid from topic /map
^C2024-07-02 18:55:46 mmajek-2204 rai.scenario_engine.tool_runner[71381] WARNING Error in running tool GetOccupancyGridTool: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:333
2024-07-02 18:55:50 mmajek-2204 rai.scenario_engine.tool_runner[71381] INFO Running tool: Ros2TopicTool with args: {'command': 'list'}
2024-07-02 18:55:50 mmajek-2204 rai.scenario_engine.tool_runner[71381] INFO Successfully ran tool: Ros2TopicTool. Output: CompletedProcess(args='ros2 topic list', returncode=0, stdout=b'/parameter_events\n/rosout\n', stderr=b'')
Traceback (most recent call last):
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_aws/llms/bedrock.py", line 666, in _prepare_input_and_invoke
    response = self.client.invoke_model(**request_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Your API request included an `assistant` message in the final position, which would pre-fill the `assistant` response. When using tools, pre-filling the `assistant` response is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmajek/projects/internal/rai-private/examples/explore_and_describe_bedrock.py", line 116, in <module>
    main()
  File "/home/mmajek/projects/internal/rai-private/examples/explore_and_describe_bedrock.py", line 111, in main
    runner.run()
  File "/home/mmajek/projects/internal/rai-private/src/rai/scenario_engine/scenario_engine.py", line 127, in run
    self._run(self.scenario)
  File "/home/mmajek/projects/internal/rai-private/src/rai/scenario_engine/scenario_engine.py", line 164, in _run
    self.llm_with_tools.invoke(
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 4588, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 248, in invoke
    self.generate_prompt(
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 677, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 534, in generate
    raise e
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 524, in generate
    self._generate_with_cache(
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 749, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_aws/chat_models/bedrock.py", line 532, in _generate
    completion, tool_calls, llm_output = self._prepare_input_and_invoke(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmajek/.cache/pypoetry/virtualenvs/rai-_GMBVdtT-py3.12/lib/python3.12/site-packages/langchain_aws/llms/bedrock.py", line 677, in _prepare_input_and_invoke
    raise ValueError(f"Error raised by bedrock service: {e}")
ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: Your API request included an `assistant` message in the final position, which would pre-fill the `assistant` response. When using tools, pre-filling the `assistant` response is not supported.
``` 

</p>
</details>

**Comment by maciejmajek** [comment]
scenario engine has been deprecated
